package yamahari.ilikewood.objectholders;

import net.minecraft.item.Item;
import net.minecraftforge.registries.ObjectHolder;
import yamahari.ilikewood.util.Constants;

@ObjectHolder(Constants.MOD_ID)
public class ModItems {
    public static final Item oak_wall = null;
    public static final Item dark_oak_wall = null;
    public static final Item spruce_wall = null;
    public static final Item birch_wall = null;
    public static final Item acacia_wall = null;
    public static final Item jungle_wall = null;

    public static final Item oak_barrel = null;
    public static final Item dark_oak_barrel = null;
    public static final Item spruce_barrel = null;
    public static final Item birch_barrel = null;
    public static final Item jungle_barrel = null;
    public static final Item acacia_barrel = null;

    public static final Item oak_chest = null;
    public static final Item dark_oak_chest = null;
    public static final Item spruce_chest = null;
    public static final Item birch_chest = null;
    public static final Item jungle_chest = null;
    public static final Item acacia_chest = null;

    public static final Item oak_bookshelf = null;
    public static final Item dark_oak_bookshelf = null;
    public static final Item spruce_bookshelf = null;
    public static final Item birch_bookshelf = null;
    public static final Item jungle_bookshelf = null;
    public static final Item acacia_bookshelf = null;

    public static final Item oak_crafting_table = null;
    public static final Item dark_oak_crafting_table = null;
    public static final Item spruce_crafting_table = null;
    public static final Item birch_crafting_table = null;
    public static final Item jungle_crafting_table = null;
    public static final Item acacia_crafting_table = null;

    public static final Item oak_panels = null;
    public static final Item dark_oak_panels = null;
    public static final Item spruce_panels = null;
    public static final Item birch_panels = null;
    public static final Item jungle_panels = null;
    public static final Item acacia_panels = null;

    public static final Item oak_post = null;
    public static final Item dark_oak_post = null;
    public static final Item spruce_post = null;
    public static final Item birch_post = null;
    public static final Item jungle_post = null;
    public static final Item acacia_post = null;

    public static final Item stripped_oak_post = null;
    public static final Item stripped_dark_oak_post = null;
    public static final Item stripped_spruce_post = null;
    public static final Item stripped_birch_post = null;
    public static final Item stripped_jungle_post = null;
    public static final Item stripped_acacia_post = null;

    public static final Item oak_lectern = null;
    public static final Item dark_oak_lectern = null;
    public static final Item spruce_lectern = null;
    public static final Item birch_lectern = null;
    public static final Item jungle_lectern = null;
    public static final Item acacia_lectern = null;

    public static final Item black_oak_bed = null;
    public static final Item black_dark_oak_bed = null;
    public static final Item black_spruce_bed = null;
    public static final Item black_birch_bed = null;
    public static final Item black_jungle_bed = null;
    public static final Item black_acacia_bed = null;
    public static final Item blue_oak_bed = null;
    public static final Item blue_dark_oak_bed = null;
    public static final Item blue_spruce_bed = null;
    public static final Item blue_birch_bed = null;
    public static final Item blue_jungle_bed = null;
    public static final Item blue_acacia_bed = null;
    public static final Item brown_oak_bed = null;
    public static final Item brown_dark_oak_bed = null;
    public static final Item brown_spruce_bed = null;
    public static final Item brown_birch_bed = null;
    public static final Item brown_jungle_bed = null;
    public static final Item brown_acacia_bed = null;
    public static final Item cyan_oak_bed = null;
    public static final Item cyan_dark_oak_bed = null;
    public static final Item cyan_spruce_bed = null;
    public static final Item cyan_birch_bed = null;
    public static final Item cyan_jungle_bed = null;
    public static final Item cyan_acacia_bed = null;
    public static final Item gray_oak_bed = null;
    public static final Item gray_dark_oak_bed = null;
    public static final Item gray_spruce_bed = null;
    public static final Item gray_birch_bed = null;
    public static final Item gray_jungle_bed = null;
    public static final Item gray_acacia_bed = null;
    public static final Item green_oak_bed = null;
    public static final Item green_dark_oak_bed = null;
    public static final Item green_spruce_bed = null;
    public static final Item green_birch_bed = null;
    public static final Item green_jungle_bed = null;
    public static final Item green_acacia_bed = null;
    public static final Item light_blue_oak_bed = null;
    public static final Item light_blue_dark_oak_bed = null;
    public static final Item light_blue_spruce_bed = null;
    public static final Item light_blue_birch_bed = null;
    public static final Item light_blue_jungle_bed = null;
    public static final Item light_blue_acacia_bed = null;
    public static final Item light_gray_oak_bed = null;
    public static final Item light_gray_dark_oak_bed = null;
    public static final Item light_gray_spruce_bed = null;
    public static final Item light_gray_birch_bed = null;
    public static final Item light_gray_jungle_bed = null;
    public static final Item light_gray_acacia_bed = null;
    public static final Item lime_oak_bed = null;
    public static final Item lime_dark_oak_bed = null;
    public static final Item lime_spruce_bed = null;
    public static final Item lime_birch_bed = null;
    public static final Item lime_jungle_bed = null;
    public static final Item lime_acacia_bed = null;
    public static final Item magenta_oak_bed = null;
    public static final Item magenta_dark_oak_bed = null;
    public static final Item magenta_spruce_bed = null;
    public static final Item magenta_birch_bed = null;
    public static final Item magenta_jungle_bed = null;
    public static final Item magenta_acacia_bed = null;
    public static final Item orange_oak_bed = null;
    public static final Item orange_dark_oak_bed = null;
    public static final Item orange_spruce_bed = null;
    public static final Item orange_birch_bed = null;
    public static final Item orange_jungle_bed = null;
    public static final Item orange_acacia_bed = null;
    public static final Item pink_oak_bed = null;
    public static final Item pink_dark_oak_bed = null;
    public static final Item pink_spruce_bed = null;
    public static final Item pink_birch_bed = null;
    public static final Item pink_jungle_bed = null;
    public static final Item pink_acacia_bed = null;
    public static final Item purple_oak_bed = null;
    public static final Item purple_dark_oak_bed = null;
    public static final Item purple_spruce_bed = null;
    public static final Item purple_birch_bed = null;
    public static final Item purple_jungle_bed = null;
    public static final Item purple_acacia_bed = null;
    public static final Item red_oak_bed = null;
    public static final Item red_dark_oak_bed = null;
    public static final Item red_spruce_bed = null;
    public static final Item red_birch_bed = null;
    public static final Item red_jungle_bed = null;
    public static final Item red_acacia_bed = null;
    public static final Item white_oak_bed = null;
    public static final Item white_dark_oak_bed = null;
    public static final Item white_spruce_bed = null;
    public static final Item white_birch_bed = null;
    public static final Item white_jungle_bed = null;
    public static final Item white_acacia_bed = null;
    public static final Item yellow_oak_bed = null;
    public static final Item yellow_dark_oak_bed = null;
    public static final Item yellow_spruce_bed = null;
    public static final Item yellow_birch_bed = null;
    public static final Item yellow_jungle_bed = null;
    public static final Item yellow_acacia_bed = null;

    public static final Item oak_scaffolding = null;
    public static final Item dark_oak_scaffolding = null;
    public static final Item spruce_scaffolding = null;
    public static final Item birch_scaffolding = null;
    public static final Item jungle_scaffolding = null;
    public static final Item acacia_scaffolding = null;
}
